optitrack_listener:
  ros__parameters:
    fixed_frame: "map"
    local_interface: '172.31.1.145'
    rigid_object_list:  'body_1'
    trackables:
      body_1:
        id: 1
        name: ground_plan_tool
    publish_tf: True
    initial_ball_position: [0.52, -0.441, -2.646]


