optitrack_listener:
  ros__parameters:
    fixed_frame: "world"
    local_interface: '172.31.1.145'
    initial_ball_position: [0.8, -0.8, -2.5]
    ball_ema_alpha: 1.0
    trajectory_save_folder: 'marker_trajectories'
    recording_x_min: 0.0
    recording_x_max: 3.0
    recording_z_min: 0.0