optitrack_listener:
  ros__parameters:
    fixed_frame: "map"
    local_interface: '172.31.1.145'
    rigid_object_list:  'body_1'
    trackables:
      body_1:
        id: 1
        name: ground_plan_tool
    publish_tf: True
    initial_ball_position: [0.52, -0.441, -2.646]

    # Exponential Moving Average parameter for ball position
    # Range: 0.0 to 1.0
    # Lower values (e.g., 0.1) = more smoothing, slower response
    # Higher values (e.g., 0.8) = less smoothing, faster response
    ball_ema_alpha: 1.0


