optitrack_listener:
  ros__parameters:
    csv_file_path: "/home/user/ros2_ws/src/ros2_optitrack_listener/recorded_pos/data.csv"
    fixed_frame: "map"
    local_interface: '192.168.1.3'
    rigid_object_list:  'body_1'
    trackables:
      body_1:
        id: 1
        name: ball
    publish_tf: True
